import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kalmuck Road Buddhist Temple</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://goo.gl/maps/2a4YX3R8hC4dyfd28">Kalmuck Road Buddhist Temple!</a>
        </h1>
        <div className={styles.imageWrapper}>
          <img
            className={styles.image}
            src="https://patch.com/img/cdn/users/86539/2012/08/raw/d3cdb28eca92f909c7a7a319c6156a3c.jpg?width=1200"
            alt="Kalmuck Road Buddhist Temple Image"
          />
        </div>
        <h2 className={styles.subTitle}>
          The website is coming soon
        </h2>
      </main>

      <footer className={styles.footer}>
        <div>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
          <p>version {process.env.version}</p>
        </div>
      </footer>
    </div>
  )
}
